// svelte-app/src/lib/components/Hero.svelte
<script>
  import { locale, t } from '$lib/i18n.js';

  function scrollTo(id) {
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  }
</script>

<section class="hero">
  <div class="hero-bg">
    <div class="orb orb-1 animate-float"></div>
    <div class="orb orb-2 animate-float" style="animation-delay: 1s"></div>
    <div class="orb orb-3 animate-float" style="animation-delay: 2s"></div>
  </div>

  <div class="container hero-content">
    <div class="hero-icons animate-fade-in">
      <!-- Smartphone icon -->
      <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" stroke-width="2"><rect x="5" y="2" width="14" height="20" rx="2" ry="2"/><line x1="12" y1="18" x2="12.01" y2="18"/></svg>
      <!-- Code icon -->
      <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" stroke-width="2"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>
    </div>

    <h1 class="text-gradient animate-fade-in" style="animation-delay:.1s">
      {t('hero.title', $locale)}
    </h1>
    <h2 class="hero-subtitle animate-fade-in" style="animation-delay:.2s">
      {t('hero.subtitle', $locale)}
    </h2>
    <p class="hero-desc animate-fade-in" style="animation-delay:.3s">
      {t('hero.description', $locale)}
    </p>

    <div class="hero-actions animate-fade-in" style="animation-delay:.4s">
      <button class="btn btn-primary" onclick={() => scrollTo('projects')}>
        {t('hero.viewWork', $locale)}
      </button>
      <button class="btn btn-outline" onclick={() => scrollTo('contact')}>
        {t('hero.getInTouch', $locale)}
      </button>
    </div>

    <button class="scroll-down animate-bounce-gentle" onclick={() => scrollTo('skills')} aria-label="Scroll down">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--fg-muted)" stroke-width="2"><polyline points="6 9 12 15 18 9"/></svg>
    </button>
  </div>
</section>

<style>
  .hero {
    min-height: 100vh; display: flex; align-items: center;
    justify-content: center; position: relative; overflow: hidden;
    padding: 5rem 0 3rem;
  }
  .hero-bg {
    position: absolute; inset: 0;
    background: var(--gradient-hero); opacity: 0.07;
  }
  .orb {
    position: absolute; border-radius: 50%;
  }
  .orb-1 { top: 15%; left: 8%; width: 80px; height: 80px; background: hsl(214 100% 60% / .12); }
  .orb-2 { bottom: 20%; right: 10%; width: 60px; height: 60px; background: hsl(197 100% 56% / .12); }
  .orb-3 { top: 50%; right: 25%; width: 48px; height: 48px; background: hsl(214 100% 60% / .06); }
  .hero-content { text-align: center; position: relative; z-index: 2; }
  .hero-icons { display: flex; gap: 0.75rem; justify-content: center; margin-bottom: 1.5rem; }
  h1 { font-size: clamp(2.5rem, 7vw, 4.2rem); font-weight: 800; margin-bottom: 0.5rem; }
  .hero-subtitle { font-size: clamp(1.2rem, 3vw, 1.8rem); color: var(--fg-muted); margin-bottom: 1rem; font-weight: 500; }
  .hero-desc {
    color: var(--fg-muted); font-size: clamp(0.95rem, 2vw, 1.15rem);
    max-width: 600px; margin: 0 auto 2.5rem; line-height: 1.8;
  }
  .hero-actions { display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap; }
  .scroll-down {
    position: absolute; bottom: 2rem; left: 50%;
    transform: translateX(-50%);
    background: none; border: none; cursor: pointer;
  }

  @media (max-width: 768px) {
    .hero { padding: 6rem 0 2rem; min-height: auto; }
    .hero-actions { flex-direction: column; align-items: center; }
    .orb-1, .orb-2, .orb-3 { display: none; }
    .scroll-down { display: none; }
  }
</style>

// base-code/src/components/Hero.tsx
import { ArrowDown, Code2, Smartphone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useTranslation } from "@/hooks/useTranslation";

const Hero = () => {
  const { t } = useTranslation();
  
  const scrollToSection = (sectionId: string) => {
    document.getElementById(sectionId)?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <section className="min-h-screen flex items-center justify-center relative overflow-hidden">
      {/* Background gradient */}
      <div className="absolute inset-0 bg-hero-gradient opacity-10" />
      
      {/* Animated background elements */}
      <div className="absolute top-20 left-10 w-20 h-20 bg-primary/10 rounded-full animate-float" />
      <div className="absolute bottom-32 right-16 w-16 h-16 bg-accent/10 rounded-full animate-float" style={{ animationDelay: '1s' }} />
      <div className="absolute top-1/2 right-1/4 w-12 h-12 bg-primary/5 rounded-full animate-float" style={{ animationDelay: '2s' }} />
      
      <div className="container mx-auto px-6 text-center relative z-10">
        <div className="animate-fade-in-up">
          <div className="flex items-center justify-center gap-2 mb-6">
            <Smartphone className="w-8 h-8 text-primary" />
            <Code2 className="w-8 h-8 text-accent" />
          </div>
          
          <h1 className="text-5xl md:text-7xl font-bold mb-6 bg-hero-gradient bg-clip-text text-transparent">
            {t('hero.title')}
          </h1>
          
          <h2 className="text-2xl md:text-3xl text-muted-foreground mb-8">
            {t('hero.subtitle')}
          </h2>
          
          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-12 leading-relaxed">
            {t('hero.description')}
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              size="lg"
              onClick={() => scrollToSection('projects')}
              className="bg-hero-gradient hover:shadow-glow transition-all duration-300"
            >
              {t('hero.viewWork')}
            </Button>
            
            <Button 
              size="lg"
              variant="outline"
              onClick={() => scrollToSection('contact')}
              className="border-primary text-primary hover:bg-primary/10"
            >
              {t('hero.getInTouch')}
            </Button>
          </div>
        </div>
        
        {/* Scroll indicator */}
        <div 
          className="absolute bottom-8 left-1/2 transform -translate-x-1/2 cursor-pointer animate-bounce"
          onClick={() => scrollToSection('skills')}
        >
          <ArrowDown className="w-6 h-6 text-muted-foreground" />
        </div>
      </div>
    </section>
  );
};

export default Hero;
