// svelte-app/src/lib/components/Skills.svelte
<script>
  import { locale, t } from '$lib/i18n.js';

  const skills = [
    { icon: 'code', key: 'flutterDev', level: 95 },
    { icon: 'phone', key: 'mobileUI', level: 90 },
    { icon: 'database', key: 'stateManagement', level: 85 },
    { icon: 'cloud', key: 'firebase', level: 88 },
    { icon: 'palette', key: 'materialDesign', level: 92 },
    { icon: 'zap', key: 'performance', level: 80 }
  ];

  const icons = {
    code: '<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>',
    phone: '<rect x="5" y="2" width="14" height="20" rx="2" ry="2"/><line x1="12" y1="18" x2="12.01" y2="18"/>',
    database: '<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/>',
    cloud: '<path d="M18 10h-1.26A8 8 0 1 0 9 20h9a5 5 0 0 0 0-10z"/>',
    palette: '<circle cx="13.5" cy="6.5" r="1.5"/><circle cx="17.5" cy="10.5" r="1.5"/><circle cx="8.5" cy="7.5" r="1.5"/><circle cx="6.5" cy="12.5" r="1.5"/><path d="M12 2C6.49 2 2 6.49 2 12s4.49 10 10 10c.55 0 1-.45 1-1v-1a1 1 0 0 1 1-1h1.5c2.76 0 5-2.24 5-5 0-5-4.49-9-9.5-9z"/>',
    zap: '<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>'
  };
</script>

<section id="skills">
  <div class="container">
    <div class="section-header">
      <h2 class="text-gradient">{t('skills.title', $locale)}</h2>
      <p>{t('skills.subtitle', $locale)}</p>
    </div>

    <div class="skills-grid">
      {#each skills as skill, i}
        <div class="card skill-card animate-fade-in" style="animation-delay: {i * 100}ms">
          <div class="skill-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" stroke-width="2">
              {@html icons[skill.icon]}
            </svg>
          </div>
          <h3>{t(`skills.${skill.key}.title`, $locale)}</h3>
          <p>{t(`skills.${skill.key}.description`, $locale)}</p>
          <div class="skill-bar-meta">
            <span>{t('skills.proficiency', $locale)}</span>
            <span class="skill-pct">{skill.level}%</span>
          </div>
          <div class="skill-bar-track">
            <div class="skill-bar-fill" style="width: {skill.level}%"></div>
          </div>
        </div>
      {/each}
    </div>
  </div>
</section>

<style>
  section { padding: 5rem 0; }
  .skills-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 1.5rem;
  }
  .skill-card { padding: 2rem; }
  .skill-icon {
    display: inline-flex; padding: 0.75rem;
    border-radius: var(--radius);
    background: var(--gradient-skill);
    margin-bottom: 1rem;
    transition: transform 0.3s;
  }
  .skill-card:hover .skill-icon { transform: scale(1.1); }
  h3 { font-size: 1.15rem; font-weight: 700; margin-bottom: 0.5rem; }
  p { color: var(--fg-muted); font-size: 0.88rem; margin-bottom: 1rem; line-height: 1.6; }
  .skill-bar-meta {
    display: flex; justify-content: space-between;
    font-size: 0.75rem; color: var(--fg-muted); margin-bottom: 0.4rem;
  }
  .skill-pct { color: var(--primary); font-weight: 600; }

  @media (max-width: 968px) {
    .skills-grid { grid-template-columns: repeat(2, 1fr); }
  }
  @media (max-width: 600px) {
    .skills-grid { grid-template-columns: 1fr; }
    .skill-card { padding: 1.5rem; }
  }
</style>

// base-code/src/components/Skills.tsx
import { Code2, Smartphone, Palette, Database, Cloud, Zap } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { useTranslation } from "@/hooks/useTranslation";

const Skills = () => {
  const { t } = useTranslation();
  
  const skills = [
    {
      icon: Code2,
      title: t('skills.flutterDev.title'),
      description: t('skills.flutterDev.description'),
      level: 95
    },
    {
      icon: Smartphone,
      title: t('skills.mobileUI.title'),
      description: t('skills.mobileUI.description'),
      level: 90
    },
    {
      icon: Database,
      title: t('skills.stateManagement.title'),
      description: t('skills.stateManagement.description'),
      level: 85
    },
    {
      icon: Cloud,
      title: t('skills.firebase.title'),
      description: t('skills.firebase.description'),
      level: 88
    },
    {
      icon: Palette,
      title: t('skills.materialDesign.title'),
      description: t('skills.materialDesign.description'),
      level: 92
    },
    {
      icon: Zap,
      title: t('skills.performance.title'),
      description: t('skills.performance.description'),
      level: 80
    }
  ];

  return (
    <section id="skills" className="py-20 px-6">
      <div className="container mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-6 bg-hero-gradient bg-clip-text text-transparent">
            {t('skills.title')}
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            {t('skills.subtitle')}
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {skills.map((skill, index) => (
            <Card 
              key={skill.title}
              className="bg-card-gradient border-border/50 hover:shadow-card transition-all duration-300 group hover:-translate-y-1"
              style={{ animationDelay: `${index * 100}ms` }}
            >
              <CardContent className="p-6">
                <div className="bg-skill-gradient p-3 rounded-lg w-fit mb-4 group-hover:scale-110 transition-transform duration-300">
                  <skill.icon className="w-6 h-6 text-primary" />
                </div>
                
                <h3 className="text-xl font-semibold mb-3 text-foreground">
                  {skill.title}
                </h3>
                
                <p className="text-muted-foreground mb-4 text-sm leading-relaxed">
                  {skill.description}
                </p>
                
                {/* Skill level bar */}
                <div className="space-y-2">
                  <div className="flex justify-between text-xs">
                    <span className="text-muted-foreground">{t('skills.proficiency')}</span>
                    <span className="text-primary font-medium">{skill.level}%</span>
                  </div>
                  <div className="w-full bg-muted rounded-full h-2">
                    <div 
                      className="bg-hero-gradient h-2 rounded-full transition-all duration-1000 ease-out"
                      style={{ width: `${skill.level}%` }}
                    />
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Skills;
